server:
      port: 8099  #配置端口
      address : localhost
      session-timeout: 30
      tomcat.max-threads: 0
      tomcat.uri-encoding: UTF-8

spring:
      datasource:  #数据库配置
                  url : jdbc:mysql://172.16.2.133:3306/business?useUnicode=true&characterEncoding=utf-8
                  username : root
                  password : root
                  driverClassName : com.mysql.jdbc.Driver
      jpa:
          properties:
                      hibernate:
                                hbm2ddl:
                                        auto: update
                                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          show-sql: true
      thymeleaf:
                cache: false
      devtools:
              restart:
                      enabled: true #热部署生效
                      additional-paths: spring-boot-jpa-page1/src/main/java  #设置重启的目录
#                      exclude: WEB-INF/**   #classpath目录下的WEB-INF文件夹内容修改不重启
# LOGGING
logging:
        level:
              com.ibatis:DEBUG

debug: true













